In [4]:
import gymnasium as gym
import numpy as np

import random

In [5]:
gamma = 0.99
epsilon = 0.1
alpha = 0.5
episodes = 500

In [6]:
Q = np.zeros((48, 4))

In [7]:
# epsilon-policy
def epsilon_greedy(state):
    if random.random() < epsilon:
        return env.action_space.sample() # explore
    else:
        return np.argmax(Q[state])

In [8]:
# Q-learning

for episode in range(episodes):

    render = (episode % 50 == 0)

    if render:
        env = gym.make("CliffWalking-v1", render_mode="human")
    else:
        env = gym.make("CliffWalking-v1")

    done = False
    state, _ = env.reset()

    episode_len = 0
    tot_reward = 0

    while not done:
        action = epsilon_greedy(state)

        next_state, reward, terminated, truncated, _ = env.step(action)
        done = terminated or truncated

        # Q-learning update
        Q[state, action] += alpha * (reward + gamma * np.max(Q[next_state]) - Q[state, action])

        state = next_state

        episode_len += 1
        tot_reward += reward

    print(f"episode={episode+1}/500 & total reward = {tot_reward} & episode len = {episode_len}")
    env.close()

episode=1/500 & total reward = -1591 & episode len = 502
episode=2/500 & total reward = -495 & episode len = 198
episode=3/500 & total reward = -66 & episode len = 66
episode=4/500 & total reward = -46 & episode len = 46
episode=5/500 & total reward = -207 & episode len = 108
episode=6/500 & total reward = -317 & episode len = 119
episode=7/500 & total reward = -89 & episode len = 89
episode=8/500 & total reward = -46 & episode len = 46
episode=9/500 & total reward = -155 & episode len = 56
episode=10/500 & total reward = -66 & episode len = 66
episode=11/500 & total reward = -35 & episode len = 35
episode=12/500 & total reward = -44 & episode len = 44
episode=13/500 & total reward = -78 & episode len = 78
episode=14/500 & total reward = -46 & episode len = 46
episode=15/500 & total reward = -36 & episode len = 36
episode=16/500 & total reward = -32 & episode len = 32
episode=17/500 & total reward = -34 & episode len = 34
episode=18/500 & total reward = -186 & episode len = 87
episode=

In [9]:
# what did our agent learn?

env = gym.make("CliffWalking-v1", render_mode="human")
state, _ = env.reset()
total_reward = 0
epsiode_len = 0
done = False

while not done:
    action = np.argmax(Q[state])
    state, reward, terminated, truncated, _ = env.step(action) #state is basically next state
    done = terminated or truncated

    epsiode_len += 1
    total_reward += reward

print(f"total reward = {total_reward} & epsiode len = {epsiode_len}")
env.close()


total reward = -13 & epsiode len = 13


In [10]:
Q[36] # Q(s, a) state = 36

array([ -12.2478977 , -112.12540109,  -13.12539973,  -13.12539661])

In [11]:
Q[35] # Q(s, a) state = 35

array([-2.96997672, -1.98993927, -1.        , -2.97009505])

In [12]:
Q

array([[ -11.69401312,  -11.66277016,  -11.59191685,  -11.77797571],
       [ -11.22460244,  -11.03852046,  -11.36150915,  -11.2405093 ],
       [ -10.66632278,  -10.48062395,  -10.5442088 ,  -10.65493298],
       [  -9.99125721,   -9.70005435,   -9.83896953,   -9.74647648],
       [  -8.93674679,   -8.93645872,   -9.15392045,   -9.27632371],
       [  -8.72186855,   -8.15743199,   -8.38865444,   -8.10751983],
       [  -7.50921803,   -7.41191555,   -7.50410865,   -8.21648841],
       [  -6.91164727,   -6.59262668,   -6.67786888,   -7.35888157],
       [  -6.09650056,   -5.69704518,   -5.69973014,   -6.61286432],
       [  -4.88898695,   -4.81589491,   -4.83370854,   -5.23824983],
       [  -3.93069564,   -3.90295924,   -3.89743462,   -5.03878774],
       [  -3.20656125,   -3.14606688,   -2.96783423,   -3.64099324],
       [ -12.05703533,  -12.106077  ,  -12.10013713,  -12.34903066],
       [ -11.40754149,  -11.35351879,  -11.35204516,  -11.80932987],
       [ -10.74091868,  -10.463900